"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { Download, FileUp, History, Loader2, Upload, AlertTriangle } from "lucide-react";
import api from "@/lib/axios";
import { showError, showSuccess } from "@/lib/toast";

type Dataset = "categories" | "subjects" | "disciplines" | "eligibility-rules";
const datasets: { value: Dataset; label: string; help: string }[] = [
  { value: "categories", label: "Subject categories", help: "Stable category codes such as CAT-STEM." },
  { value: "subjects", label: "Subjects", help: "Subject codes reference a category code, never an internal ID." },
  { value: "disciplines", label: "Academic disciplines", help: "Qualification disciplines such as DISC-MATH." },
  { value: "eligibility-rules", label: "Teaching eligibility", help: "Discipline-to-subject direct or conditional rules." },
];

export default function AcademicImportExportPage() {
  const [dataset, setDataset] = useState<Dataset>("categories"); const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false); const [preview, setPreview] = useState<any>(null); const [history, setHistory] = useState<any[]>([]);
  const loadHistory = async () => { try { const { data } = await api.get("/admin/academic-framework/import-export/history"); setHistory(data.jobs || []); } catch { /* history is supplementary */ } };
  useEffect(() => { void loadHistory(); }, []);
  const form = () => { const data = new FormData(); if (file) data.append("file", file); return data; };
  const dryRun = async () => { if (!file) return showError("Choose a CSV file first"); setBusy(true); try { const { data } = await api.post(`/admin/academic-framework/import-export/dry-run/${dataset}`, form()); setPreview(data); data.errors?.length ? showError("The preview found validation errors") : showSuccess("CSV validated. Review the preview before committing."); } catch (error) { showError(error, "Could not validate this CSV"); } finally { setBusy(false); } };
  const commit = async () => { if (!file || !preview || preview.errors?.length) return; if (!window.confirm("Commit this validated CSV to the academic framework? Existing rows with matching codes will be updated.")) return; setBusy(true); try { const { data } = await api.post(`/admin/academic-framework/import-export/commit/${dataset}`, form()); showSuccess(`Import complete: ${data.created} created, ${data.updated} updated.`); setPreview(null); setFile(null); await loadHistory(); } catch (error) { showError(error, "The import could not be committed"); } finally { setBusy(false); } };
  const download = async (kind: "templates" | "export") => { try { const response = await api.get(`/admin/academic-framework/import-export/${kind}/${dataset}`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${dataset}-${kind}.csv`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { showError(error, "Could not download CSV"); } };
  const onFile = (event: ChangeEvent<HTMLInputElement>) => { const next = event.target.files?.[0] || null; if (next && !next.name.toLowerCase().endsWith(".csv")) { showError("Upload a .csv file"); return; } setFile(next); setPreview(null); };
  return <main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><header><p className="text-sm font-bold uppercase tracking-[.14em] text-[#016EF8]">Academic governance</p><h1 className="mt-1 text-3xl font-extrabold text-slate-900">Import & export</h1><p className="mt-2 max-w-3xl text-slate-600">Validate a code-based CSV before committing it. Imports never require or expose MongoDB IDs.</p></header>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><label className="block text-sm font-bold text-slate-800" htmlFor="dataset">Dataset</label><select id="dataset" value={dataset} onChange={(event) => { setDataset(event.target.value as Dataset); setPreview(null); }} className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-slate-900 focus:border-blue-600 focus:outline-none focus:ring-4 focus:ring-blue-100">{datasets.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><p className="mt-2 text-sm text-slate-600">{datasets.find((item) => item.value === dataset)?.help}</p>
      <div className="mt-5 flex flex-wrap gap-3"><button onClick={() => void download("templates")} className="inline-flex items-center gap-2 rounded-lg border border-blue-200 px-3 py-2 text-sm font-bold text-[#0329B2] hover:bg-blue-50"><Download className="h-4 w-4" />Template</button><button onClick={() => void download("export")} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"><Download className="h-4 w-4" />Export</button></div>
      <label className="mt-6 flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-slate-300 p-6 text-center hover:border-blue-400" htmlFor="csv-file"><FileUp className="h-7 w-7 text-[#016EF8]" /><span className="mt-2 font-bold text-slate-800">{file?.name || "Choose a CSV file"}</span><span className="mt-1 text-xs text-slate-500">Maximum 2 MB</span><input id="csv-file" className="sr-only" type="file" accept=".csv,text/csv" onChange={onFile} /></label>
      <button disabled={!file || busy} onClick={() => void dryRun()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#0329B2] px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}Validate CSV</button></div>
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Import history</h2><div className="mt-3 space-y-3">{history.length ? history.slice(0, 6).map((job) => <div key={job._id} className="flex items-start justify-between gap-3 border-b border-slate-100 pb-3 text-sm"><div><p className="font-semibold text-slate-800">{job.dataset}</p><p className="text-slate-500">{job.filename || "CSV import"} · {new Date(job.createdAt).toLocaleString()}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">{job.status}</span></div>) : <p className="py-6 text-sm text-slate-500">No academic imports recorded yet.</p>}</div></div></section>
    {preview && <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">Validation preview</h2><p className="mt-1 text-sm text-slate-600">{preview.validRows} valid of {preview.totalRows} rows.</p>{preview.errors?.length > 0 ? <div className="mt-4 rounded-lg bg-red-50 p-4 text-sm text-red-800"><div className="flex items-center gap-2 font-bold"><AlertTriangle className="h-4 w-4" />Correct these errors before committing</div><ul className="mt-2 list-disc pl-5">{preview.errors.map((error: any, index: number) => <li key={index}>Row {error.row}{error.field ? ` (${error.field})` : ""}: {error.message}</li>)}</ul></div> : <button disabled={busy} onClick={() => void commit()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}Commit validated import</button>}</section>}
  </main>;
}
