export type EmailEventDefinition = {
  event: string;
  recipient: string;
  trigger: string;
  exampleSubject: string;
  category: string;
};

export const EMAIL_EVENTS: EmailEventDefinition[] = [
  { event: "user_registered", recipient: "Student/Tutor", trigger: "Immediately after registration", exampleSubject: "Welcome to TUTORERA", category: "Auth" },
  { event: "email_verification_requested", recipient: "User", trigger: "Immediately after signup or email change", exampleSubject: "Verify Your Email Address", category: "Auth" },
  { event: "email_verified", recipient: "User", trigger: "After successful verification", exampleSubject: "Email Verified Successfully", category: "Auth" },
  { event: "otp_requested", recipient: "User", trigger: "Immediately when OTP is requested", exampleSubject: "Your TUTORERA Verification Code", category: "Auth" },
  { event: "password_reset_requested", recipient: "User", trigger: "Immediately after reset request", exampleSubject: "Reset Your TUTORERA Password", category: "Auth" },
  { event: "password_changed", recipient: "User", trigger: "Immediately after password change", exampleSubject: "Your Password Has Been Changed", category: "Auth" },
  { event: "new_login_detected", recipient: "User", trigger: "On suspicious/new-device login", exampleSubject: "New Login to Your TUTORERA Account", category: "Auth" },
  { event: "student_request_created", recipient: "Student/Parent", trigger: "After tutoring requirement is successfully posted", exampleSubject: "Your Tutoring Request Is Live", category: "Student Requests" },
  { event: "student_request_abandoned_1d", recipient: "Student/Parent", trigger: "1 day after an unfinished request draft", exampleSubject: "Finish your TUTORERA tuition request", category: "Student Requests" },
  { event: "student_request_abandoned_3d", recipient: "Student/Parent", trigger: "3 days after an unfinished request draft", exampleSubject: "Still looking for a tutor?", category: "Student Requests" },
  { event: "student_request_abandoned_7d", recipient: "Student/Parent", trigger: "7 days after an unfinished request draft", exampleSubject: "Last reminder: post your tuition request", category: "Student Requests" },
  { event: "student_direct_booking_abandoned_1d", recipient: "Student/Parent", trigger: "1 day after an unfinished direct booking attempt", exampleSubject: "Finish your TUTORERA tuition request", category: "Student Requests" },
  { event: "student_direct_booking_abandoned_3d", recipient: "Student/Parent", trigger: "3 days after an unfinished direct booking attempt", exampleSubject: "Still looking for a tutor?", category: "Student Requests" },
  { event: "student_direct_booking_abandoned_7d", recipient: "Student/Parent", trigger: "7 days after an unfinished direct booking attempt", exampleSubject: "Last reminder: post your tuition request", category: "Student Requests" },
  { event: "student_request_under_review", recipient: "Student", trigger: "If moderation/review is required", exampleSubject: "Your Tutoring Request Is Under Review", category: "Student Requests" },
  { event: "student_request_approved", recipient: "Student", trigger: "When approved", exampleSubject: "Your Tutoring Request Has Been Approved", category: "Student Requests" },
  { event: "student_request_rejected", recipient: "Student", trigger: "When rejected", exampleSubject: "Action Required on Your Tutoring Request", category: "Student Requests" },
  { event: "matching_tutors_found", recipient: "Student", trigger: "After matching engine finds suitable tutors", exampleSubject: "Tutors Are Available for Your Request", category: "Matching" },
  { event: "new_tutoring_opportunity", recipient: "Relevant Tutors", trigger: "When a matching student requirement is published", exampleSubject: "New Tutoring Opportunity Available", category: "Matching" },
  { event: "tutor_offer_submitted", recipient: "Tutor", trigger: "Immediately after tutor submits an offer", exampleSubject: "Your Offer Has Been Submitted", category: "Offers" },
  { event: "tutor_offer_received", recipient: "Student", trigger: "Immediately when a tutor submits an offer", exampleSubject: "You Received a New Tutor Offer", category: "Offers" },
  { event: "offer_updated", recipient: "Student", trigger: "When tutor changes fee/terms", exampleSubject: "A Tutor Updated Their Offer", category: "Offers" },
  { event: "offer_withdrawn", recipient: "Student", trigger: "When tutor withdraws offer", exampleSubject: "Tutor Offer Withdrawn", category: "Offers" },
  { event: "tutor_shortlisted", recipient: "Tutor", trigger: "When student shortlists tutor", exampleSubject: "You Have Been Shortlisted", category: "Offers" },
  { event: "offer_accepted", recipient: "Tutor + Student", trigger: "Immediately when student accepts offer", exampleSubject: "Tutor Offer Accepted", category: "Offers" },
  { event: "offer_declined", recipient: "Tutor", trigger: "When student declines offer", exampleSubject: "Update on Your Tutor Offer", category: "Offers" },
  { event: "booking_requested", recipient: "Tutor", trigger: "When student sends booking request", exampleSubject: "New Booking Request", category: "Bookings" },
  { event: "booking_confirmed", recipient: "Both", trigger: "When booking becomes confirmed", exampleSubject: "Your TUTORERA Booking Is Confirmed", category: "Bookings" },
  { event: "booking_rescheduled", recipient: "Both", trigger: "Immediately after schedule change", exampleSubject: "Your Tutoring Session Has Been Rescheduled", category: "Bookings" },
  { event: "booking_cancelled", recipient: "Both", trigger: "Immediately after cancellation", exampleSubject: "Tutoring Booking Cancelled", category: "Bookings" },
  { event: "class_reminder_24h", recipient: "Both", trigger: "24 hours before class", exampleSubject: "Your Class Is Tomorrow", category: "Classes" },
  { event: "class_reminder_1h", recipient: "Both", trigger: "1 hour before class", exampleSubject: "Your TUTORERA Class Starts Soon", category: "Classes" },
  { event: "class_started", recipient: "Student/Tutor", trigger: "At scheduled start, if needed", exampleSubject: "Your Tutoring Session Is Starting", category: "Classes" },
  { event: "class_completed", recipient: "Both", trigger: "After session is marked complete", exampleSubject: "Tutoring Session Completed", category: "Classes" },
  { event: "payment_created", recipient: "Student", trigger: "When payment invoice/order is generated", exampleSubject: "Payment Request from TUTORERA", category: "Payments" },
  { event: "payment_pending", recipient: "Student", trigger: "After payment starts but is not confirmed", exampleSubject: "Your Payment Is Pending", category: "Payments" },
  { event: "payment_abandoned_1d", recipient: "Student", trigger: "1 day after booking payment remains pending", exampleSubject: "Complete payment to confirm your tutor booking", category: "Payments" },
  { event: "payment_abandoned_3d", recipient: "Student", trigger: "3 days after booking payment remains pending", exampleSubject: "Your selected tutor booking is waiting", category: "Payments" },
  { event: "payment_abandoned_7d", recipient: "Student", trigger: "7 days after booking payment remains pending", exampleSubject: "Last reminder: confirm your tutor booking", category: "Payments" },
  { event: "payment_successful", recipient: "Student", trigger: "Immediately after gateway confirmation", exampleSubject: "Payment Successful", category: "Payments" },
  { event: "payment_receipt", recipient: "Student", trigger: "After successful payment", exampleSubject: "Your TUTORERA Payment Receipt", category: "Payments" },
  { event: "payment_failed", recipient: "Student", trigger: "Immediately after failed transaction", exampleSubject: "Payment Unsuccessful", category: "Payments" },
  { event: "payment_refunded", recipient: "Student", trigger: "After successful refund", exampleSubject: "Your Refund Has Been Processed", category: "Payments" },
  { event: "tutor_earning_recorded", recipient: "Tutor", trigger: "When completed lesson generates earnings", exampleSubject: "New Earnings Added", category: "Payouts" },
  { event: "tutor_payout_requested", recipient: "Tutor", trigger: "After payout request", exampleSubject: "Payout Request Received", category: "Payouts" },
  { event: "tutor_payout_processing", recipient: "Tutor", trigger: "When payout is processed", exampleSubject: "Your Payout Is Being Processed", category: "Payouts" },
  { event: "tutor_payout_completed", recipient: "Tutor", trigger: "After payout confirmation", exampleSubject: "Your Tutor Payout Is Complete", category: "Payouts" },
  { event: "profile_submitted", recipient: "Tutor", trigger: "After tutor profile submission", exampleSubject: "Tutor Profile Submitted", category: "Tutor Verification" },
  { event: "profile_abandoned_1d", recipient: "Tutor", trigger: "1 day after incomplete tutor onboarding", exampleSubject: "Complete your TUTORERA tutor application", category: "Tutor Verification" },
  { event: "profile_abandoned_3d", recipient: "Tutor", trigger: "3 days after incomplete tutor onboarding", exampleSubject: "Your TUTORERA tutor application is still waiting", category: "Tutor Verification" },
  { event: "profile_abandoned_7d", recipient: "Tutor", trigger: "7 days after incomplete tutor onboarding", exampleSubject: "Last reminder: finish your TUTORERA tutor application", category: "Tutor Verification" },
  { event: "profile_approved", recipient: "Tutor", trigger: "After verification/approval", exampleSubject: "Your Tutor Profile Is Approved", category: "Tutor Verification" },
  { event: "profile_revision_required", recipient: "Tutor", trigger: "When documents/profile need changes", exampleSubject: "Action Required on Your Tutor Profile", category: "Tutor Verification" },
  { event: "police_verification_required", recipient: "Tutor", trigger: "For in-person/home tutoring eligibility", exampleSubject: "Police Verification Required", category: "Tutor Verification" },
  { event: "police_verification_received", recipient: "Tutor", trigger: "After upload/submission", exampleSubject: "Verification Document Received", category: "Tutor Verification" },
  { event: "police_verification_approved", recipient: "Tutor", trigger: "After approval", exampleSubject: "Police Verification Approved", category: "Tutor Verification" },
  { event: "document_expiring", recipient: "Tutor", trigger: "Before verification document expiry", exampleSubject: "Your Verification Document Is Expiring", category: "Tutor Verification" },
  { event: "review_requested", recipient: "Student", trigger: "After completed class/booking", exampleSubject: "How Was Your Tutor?", category: "Reviews" },
  { event: "review_received", recipient: "Tutor", trigger: "When review is published", exampleSubject: "You Received a New Review", category: "Reviews" },
  { event: "complaint_submitted", recipient: "Complainant", trigger: "Immediately after complaint", exampleSubject: "We Received Your Complaint", category: "Support" },
  { event: "complaint_assigned", recipient: "Relevant user", trigger: "When support begins investigation", exampleSubject: "Update on Your TUTORERA Case", category: "Support" },
  { event: "account_warning", recipient: "User", trigger: "When policy warning is issued", exampleSubject: "Important Notice About Your Account", category: "Account" },
  { event: "account_suspended", recipient: "User", trigger: "Immediately after suspension", exampleSubject: "Your TUTORERA Account Has Been Suspended", category: "Account" },
  { event: "account_reactivated", recipient: "User", trigger: "After restoration", exampleSubject: "Your TUTORERA Account Has Been Reactivated", category: "Account" },
  { event: "support_ticket_created", recipient: "User", trigger: "Immediately after support request", exampleSubject: "Support Request Received", category: "Support" },
  { event: "support_ticket_replied", recipient: "User", trigger: "Whenever support replies", exampleSubject: "Update on Your Support Request", category: "Support" },
];

export function normalizeEmailEventName(eventType: string) {
  const aliases: Record<string, string> = {
    "auth.user.registered": "user_registered",
    "auth.email.verification_requested": "email_verification_requested",
    "auth.email.verified": "email_verified",
    "auth.password.reset_requested": "password_reset_requested",
    "auth.password.changed": "password_changed",
    "student.request.created": "student_request_created",
    "student.request.abandoned_reminder_1d": "student_request_abandoned_1d",
    "student.request.abandoned_reminder_3d": "student_request_abandoned_3d",
    "student.request.abandoned_reminder_7d": "student_request_abandoned_7d",
    "student.direct_booking.abandoned_reminder_1d": "student_direct_booking_abandoned_1d",
    "student.direct_booking.abandoned_reminder_3d": "student_direct_booking_abandoned_3d",
    "student.direct_booking.abandoned_reminder_7d": "student_direct_booking_abandoned_7d",
    "tutor.application.abandoned_reminder_1d": "profile_abandoned_1d",
    "tutor.application.abandoned_reminder_3d": "profile_abandoned_3d",
    "tutor.application.abandoned_reminder_7d": "profile_abandoned_7d",
    "tutor.profile.submitted": "profile_submitted",
    "tutor.profile.approved": "profile_approved",
    "tutor.verification.required": "profile_revision_required",
    "tutor.verification.approved": "profile_approved",
    "offer.created": "tutor_offer_submitted",
    "offer.updated": "offer_updated",
    "offer.accepted": "offer_accepted",
    "offer.declined": "offer_declined",
    "offer.withdrawn": "offer_withdrawn",
    "booking.created": "booking_requested",
    "booking.confirmed": "booking_confirmed",
    "booking.payment.abandoned_reminder_1d": "payment_abandoned_1d",
    "booking.payment.abandoned_reminder_3d": "payment_abandoned_3d",
    "booking.payment.abandoned_reminder_7d": "payment_abandoned_7d",
    "booking.rescheduled": "booking_rescheduled",
    "booking.cancelled": "booking_cancelled",
    "booking.completed": "class_completed",
    "payment.created": "payment_created",
    "payment.pending": "payment_pending",
    "payment.succeeded": "payment_successful",
    "payment.failed": "payment_failed",
    "payment.refunded": "payment_refunded",
    "payout.requested": "tutor_payout_requested",
    "payout.processing": "tutor_payout_processing",
    "payout.completed": "tutor_payout_completed",
    "payout.failed": "tutor_payout_processing",
    "review.requested": "review_requested",
    "review.created": "review_received",
    "support.ticket.created": "support_ticket_created",
    "support.ticket.updated": "support_ticket_replied",
    "account.warning": "account_warning",
    "account.suspended": "account_suspended",
    "account.reactivated": "account_reactivated",
  };
  return aliases[eventType] || eventType;
}
