/**
 * TUTORERA Central Notification & Event Registry
 *
 * Governs multi-channel routing (Email, In-App, Push, SMS) for all canonical marketplace events.
 * Implements priority levels, audience boundaries, throttling policies, and template mappings.
 */

export type NotificationChannel = "inApp" | "push" | "email" | "sms";

export type EventPriority = "low" | "normal" | "high" | "critical";

export type EventAudience = "student" | "tutor" | "parent" | "admin" | "system";

export interface EventRegistryEntry {
  event: string;
  category: string;
  audience: EventAudience[];
  channels: {
    inApp: boolean;
    push: boolean;
    email: boolean;
    sms: boolean;
  };
  priority: EventPriority;
  throttleMs?: number;
  templateId?: string;
  isTransactional: boolean;
  description: string;
}

export const NOTIFICATION_EVENT_REGISTRY: Record<string, EventRegistryEntry> = {
  // ── 1. Authentication & Account ──────────────────────────────────────────
  "auth.registered": {
    event: "auth.registered",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "high",
    templateId: "auth_welcome",
    isTransactional: true,
    description: "Welcome to TUTORERA after successful registration",
  },
  "auth.email.verify_requested": {
    event: "auth.email.verify_requested",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: false, push: false, email: true, sms: false },
    priority: "critical",
    templateId: "auth_verify_email",
    isTransactional: true,
    description: "Verification code or link for email confirmation",
  },
  "auth.email.verified": {
    event: "auth.email.verified",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: false, email: false, sms: false },
    priority: "normal",
    isTransactional: false,
    description: "In-app confirmation that email was verified",
  },
  "auth.otp_requested": {
    event: "auth.otp_requested",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: false, push: false, email: true, sms: true },
    priority: "critical",
    templateId: "auth_otp_code",
    isTransactional: true,
    description: "One-time password for phone or 2FA login",
  },
  "auth.password.reset_requested": {
    event: "auth.password.reset_requested",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: false, push: false, email: true, sms: false },
    priority: "critical",
    templateId: "password_reset_code",
    isTransactional: true,
    description: "Password reset OTP email",
  },
  "auth.password.changed": {
    event: "auth.password.changed",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "password_changed_alert",
    isTransactional: true,
    description: "Security notification when password was modified",
  },
  "auth.new_device_login": {
    event: "auth.new_device_login",
    category: "auth",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "new_login_alert",
    isTransactional: true,
    description: "Alert on unrecognized browser or location login",
  },
  "account.suspended": {
    event: "account.suspended",
    category: "account",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "account_suspended_notice",
    isTransactional: true,
    description: "Notice of account suspension due to compliance or safety",
  },
  "account.reactivated": {
    event: "account.reactivated",
    category: "account",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "high",
    templateId: "account_reactivated_notice",
    isTransactional: true,
    description: "Notice of account restoration",
  },
  "admin.user_registered": {
    event: "admin.user_registered",
    category: "admin",
    audience: ["admin", "system"],
    channels: { inApp: false, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "admin_new_user",
    isTransactional: true,
    description: "Platform admin notification of new signup",
  },

  // ── 2. Student Tuition Requests ──────────────────────────────────────────
  "request.created": {
    event: "request.created",
    category: "request",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "request_created",
    isTransactional: true,
    description: "Confirmation that student tuition requirement was posted",
  },
  "request.published": {
    event: "request.published",
    category: "request",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "request_published",
    isTransactional: true,
    description: "Student request is live on the marketplace",
  },
  "request.matches_found": {
    event: "request.matches_found",
    category: "matching",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: false, sms: false },
    priority: "normal",
    isTransactional: false,
    description: "Tutors matching student request are available",
  },
  "request.first_offer_received": {
    event: "request.first_offer_received",
    category: "offer",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "first_offer_received",
    isTransactional: true,
    description: "First tutor offer submitted on student request",
  },
  "request.three_offers_reached": {
    event: "request.three_offers_reached",
    category: "offer",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "normal",
    templateId: "offers_to_compare",
    isTransactional: false,
    description: "Three qualified offers ready for comparison",
  },
  "request.zero_offer": {
    event: "request.zero_offer",
    category: "request",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "high",
    templateId: "request_zero_offer",
    isTransactional: false,
    description: "Expanding search when no tutor offers within SLA",
  },
  "request.expiring": {
    event: "request.expiring",
    category: "request",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "normal",
    templateId: "request_expiring",
    isTransactional: false,
    description: "Student request expires in 48 hours",
  },
  "request.expired": {
    event: "request.expired",
    category: "request",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "low",
    templateId: "request_expired",
    isTransactional: false,
    description: "Student request expired with option to repost",
  },
  "request.reposted": {
    event: "request.reposted",
    category: "request",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "request_reposted",
    isTransactional: true,
    description: "Student request republished to marketplace",
  },

  // ── 3. Abandoned Journey Recovery ────────────────────────────────────────
  "request.abandoned_6h": {
    event: "request.abandoned_6h",
    category: "growth",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "request_abandoned_6h",
    isTransactional: false,
    description: "Finish your tuition request draft (6h)",
  },
  "request.abandoned_24h": {
    event: "request.abandoned_24h",
    category: "growth",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "request_abandoned_24h",
    isTransactional: false,
    description: "Still looking for a tutor? (24h)",
  },
  "request.abandoned_72h": {
    event: "request.abandoned_72h",
    category: "growth",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "low",
    templateId: "request_abandoned_72h",
    isTransactional: false,
    description: "Your tutor search is waiting — continue when ready (72h)",
  },
  "request.abandoned_168h": {
    event: "request.abandoned_168h",
    category: "growth",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "low",
    templateId: "request_abandoned_168h",
    isTransactional: false,
    description: "Your tutor search is waiting — continue when ready (168h)",
  },
  "booking.payment_abandoned_1h": {
    event: "booking.payment_abandoned_1h",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "payment_abandoned_1h",
    isTransactional: true,
    description: "Complete payment to confirm tutor slot (1h)",
  },
  "booking.payment_abandoned_24h": {
    event: "booking.payment_abandoned_24h",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "payment_abandoned_24h",
    isTransactional: false,
    description: "Your selected tutor booking is waiting for payment (24h)",
  },
  "booking.payment_abandoned_48h": {
    event: "booking.payment_abandoned_48h",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "normal",
    templateId: "payment_abandoned_48h",
    isTransactional: false,
    description: "Your booking will expire soon (48h)",
  },
  "booking.payment_abandoned_72h": {
    event: "booking.payment_abandoned_72h",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "payment_abandoned_72h",
    isTransactional: false,
    description: "Your booking is waiting for payment (72h)",
  },
  "booking.payment_abandoned_168h": {
    event: "booking.payment_abandoned_168h",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "low",
    templateId: "payment_abandoned_168h",
    isTransactional: false,
    description: "Your booking is waiting for payment (168h)",
  },
  "tutor.application_abandoned_24h": {
    event: "tutor.application_abandoned_24h",
    category: "growth",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "tutor_app_abandoned_24h",
    isTransactional: false,
    description: "Finish your tutor application (24h)",
  },
  "tutor.application_abandoned_72h": {
    event: "tutor.application_abandoned_72h",
    category: "growth",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "low",
    templateId: "tutor_app_abandoned_72h",
    isTransactional: false,
    description: "Your tutor application is still waiting (72h)",
  },
  "tutor.application_abandoned_168h": {
    event: "tutor.application_abandoned_168h",
    category: "growth",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "low",
    templateId: "tutor_app_abandoned_168h",
    isTransactional: false,
    description: "Your tutor application is still waiting (168h)",
  },

  // ── 4. Offers & Structured Negotiation ───────────────────────────────────
  "offer.received": {
    event: "offer.received",
    category: "offer",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "new_offer_received",
    isTransactional: true,
    description: "Student received new tutor offer",
  },
  "offer.student_countered": {
    event: "offer.student_countered",
    category: "negotiation",
    audience: ["tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "student_counter_offer",
    isTransactional: true,
    description: "Student proposed counter rate or schedule",
  },
  "offer.tutor_countered": {
    event: "offer.tutor_countered",
    category: "negotiation",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "tutor_counter_offer",
    isTransactional: true,
    description: "Tutor responded with counter offer",
  },
  "offer.accepted": {
    event: "offer.accepted",
    category: "offer",
    audience: ["student", "tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "offer_accepted",
    isTransactional: true,
    description: "Offer accepted by student; booking generated",
  },
  "offer.declined": {
    event: "offer.declined",
    category: "offer",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "offer_declined",
    isTransactional: true,
    description: "Offer declined by student",
  },
  "offer.withdrawn": {
    event: "offer.withdrawn",
    category: "offer",
    audience: ["student"],
    channels: { inApp: true, push: false, email: false, sms: false },
    priority: "low",
    isTransactional: false,
    description: "Tutor withdrew an unaccepted offer",
  },

  // ── 5. Bookings & Sessions ───────────────────────────────────────────────
  "booking.created": {
    event: "booking.created",
    category: "booking",
    audience: ["student", "tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "booking_created",
    isTransactional: true,
    description: "New booking created, awaiting payment or tutor review",
  },
  "booking.confirmed": {
    event: "booking.confirmed",
    category: "booking",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "booking_confirmed",
    isTransactional: true,
    description: "Booking is fully paid and confirmed on schedule",
  },
  "booking.rescheduled": {
    event: "booking.rescheduled",
    category: "booking",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "booking_rescheduled",
    isTransactional: true,
    description: "Session date/time was rescheduled",
  },
  "booking.cancelled": {
    event: "booking.cancelled",
    category: "booking",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "booking_cancelled",
    isTransactional: true,
    description: "Booking cancellation by student, tutor, or admin",
  },
  "booking.session_reminder_24h": {
    event: "booking.session_reminder_24h",
    category: "session",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "normal",
    templateId: "session_reminder_24h",
    isTransactional: true,
    description: "Session is tomorrow reminder",
  },
  "booking.session_reminder_1h": {
    event: "booking.session_reminder_1h",
    category: "session",
    audience: ["student", "tutor"],
    channels: { inApp: true, push: true, email: false, sms: false },
    priority: "high",
    isTransactional: false,
    description: "Push/in-app alert: session starts in 1 hour (no email)",
  },
  "booking.session_reminder_10m": {
    event: "booking.session_reminder_10m",
    category: "session",
    audience: ["student", "tutor"],
    channels: { inApp: true, push: true, email: false, sms: false },
    priority: "high",
    isTransactional: false,
    description: "Push alert: session starts in 10 minutes (no email)",
  },
  "booking.completed": {
    event: "booking.completed",
    category: "session",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "session_completed",
    isTransactional: true,
    description: "Lesson marked completed",
  },
  "booking.no_show": {
    event: "booking.no_show",
    category: "safety",
    audience: ["student", "tutor", "admin"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "session_attendance_issue",
    isTransactional: true,
    description: "Action required: session attendance issue / no-show",
  },

  // ── 6. Payments & Payouts ────────────────────────────────────────────────
  "payment.succeeded": {
    event: "payment.succeeded",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "payment_receipt",
    isTransactional: true,
    description: "Official payment receipt & booking confirmation",
  },
  "payment.failed": {
    event: "payment.failed",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "payment_failed",
    isTransactional: true,
    description: "Payment transaction declined or failed",
  },
  "payment.refunded": {
    event: "payment.refunded",
    category: "payment",
    audience: ["student", "parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "refund_processed",
    isTransactional: true,
    description: "Official confirmation of refund settlement",
  },
  "payout.requested": {
    event: "payout.requested",
    category: "payout",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "payout_requested",
    isTransactional: true,
    description: "Tutor submitted a payout request",
  },
  "payout.processing": {
    event: "payout.processing",
    category: "payout",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "payout_processing",
    isTransactional: true,
    description: "Payout approved and sent to bank gateway",
  },
  "payout.completed": {
    event: "payout.completed",
    category: "payout",
    audience: ["tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "payout_completed",
    isTransactional: true,
    description: "Payout confirmed deposited to tutor bank account",
  },
  "payout.failed": {
    event: "payout.failed",
    category: "payout",
    audience: ["tutor", "admin"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "payout_failed",
    isTransactional: true,
    description: "Bank rejection or invalid IBAN / account issue",
  },
  "payout.held": {
    event: "payout.held",
    category: "payout",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "high",
    templateId: "payout_held",
    isTransactional: true,
    description: "Payout temporarily held for compliance or review",
  },

  // ── 7. Verification & Home Tuition ───────────────────────────────────────
  "verification.submitted": {
    event: "verification.submitted",
    category: "verification",
    audience: ["tutor"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "verification_submitted",
    isTransactional: true,
    description: "Tutor documents submitted for review",
  },
  "verification.approved": {
    event: "verification.approved",
    category: "verification",
    audience: ["tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "tutor_approved",
    isTransactional: true,
    description: "Tutor profile approved and live on marketplace",
  },
  "verification.rejected": {
    event: "verification.rejected",
    category: "verification",
    audience: ["tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "verification_rejected",
    isTransactional: true,
    description: "Document requires attention / resubmission",
  },
  "home_tuition.eligibility_granted": {
    event: "home_tuition.eligibility_granted",
    category: "verification",
    audience: ["tutor"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "home_tuition_approved",
    isTransactional: true,
    description: "Police verification verified — home tuition unlocked",
  },

  // ── 8. Safety, Disputes & Child Alerts ───────────────────────────────────
  "safety.case_created": {
    event: "safety.case_created",
    category: "safety",
    audience: ["student", "tutor", "parent", "admin"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "critical",
    templateId: "safety_case_created",
    isTransactional: true,
    description: "Trust & Safety report logged with case number",
  },
  "safety.case_resolved": {
    event: "safety.case_resolved",
    category: "safety",
    audience: ["student", "tutor", "parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "high",
    templateId: "safety_case_resolved",
    isTransactional: true,
    description: "Safety or dispute case finalized",
  },
  "child.booking.confirmed": {
    event: "child.booking.confirmed",
    category: "booking",
    audience: ["parent"],
    channels: { inApp: true, push: true, email: true, sms: false },
    priority: "high",
    templateId: "child_booking_confirmed",
    isTransactional: true,
    description: "Parent notified when tutor booking is confirmed for child",
  },
  "child.session_reminder": {
    event: "child.session_reminder",
    category: "session",
    audience: ["parent"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "child_session_reminder",
    isTransactional: true,
    description: "Parent notified that child's session is tomorrow",
  },
  "review.requested": {
    event: "review.requested",
    category: "review",
    audience: ["student"],
    channels: { inApp: true, push: false, email: true, sms: false },
    priority: "normal",
    templateId: "review_requested",
    isTransactional: true,
    description: "Feedback request after completed lesson",
  },
};

export function getEventRegistryEntry(eventName: string): EventRegistryEntry | undefined {
  return NOTIFICATION_EVENT_REGISTRY[eventName];
}
