"use client";

import { useEffect, useState } from "react";
import { Archive, Pencil, Plus, Save, X } from "lucide-react";
import api from "@/lib/axios";
import { showError, showSuccess } from "@/lib/toast";
type Category = { _id: string; code: string; name: string; description?: string; displayOrder: number };
const empty = { code: "", name: "", description: "", displayOrder: "0" };
export default function SubjectCategoriesPage() {
  const [items, setItems] = useState<Category[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [open, setOpen] = useState(false);
  const load = async () => { setLoading(true); try { const { data } = await api.get("/admin/academic-framework/categories?status=active&limit=100"); setItems(data.categories || []); } catch (error) { showError(error, "Could not load subject categories"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []); const reset = () => { setForm(empty); setEditing(null); setOpen(false); };
  const save = async () => { if (!form.name.trim()) return showError("Category name is required"); setSaving(true); const payload = { ...form, displayOrder: Number(form.displayOrder) || 0 }; try { if (editing) { await api.patch(`/admin/academic-framework/categories/${editing}`, payload); showSuccess("Category updated"); } else { await api.post("/admin/academic-framework/categories", payload); showSuccess("Category created"); } reset(); await load(); } catch (error) { showError(error, "Could not save category"); } finally { setSaving(false); } };
  const archive = async (item: Category) => { if (!window.confirm(`Archive ${item.name}? Existing subjects remain readable.`)) return; try { await api.patch(`/admin/academic-framework/categories/${item._id}`, { status: "archived" }); showSuccess("Category archived"); await load(); } catch (error) { showError(error, "Could not archive category"); } };
  return <main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#016EF8]">Academic framework</p><h1 className="mt-1 text-3xl font-extrabold text-slate-900">Subject Categories</h1><p className="mt-2 text-slate-600">Categories organise the public subject catalogue. They do not determine teaching eligibility.</p><button onClick={() => { reset(); setOpen(true); }} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#0329B2] px-4 py-2.5 font-bold text-white"><Plus className="h-4 w-4" />New category</button>
    {open && <section className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold text-slate-900">{editing ? "Edit category" : "Create category"}</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold text-slate-700">Stable code<input disabled={Boolean(editing)} value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="CAT-STEM" className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal disabled:bg-slate-100" /></label><label className="text-sm font-bold text-slate-700">Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label><label className="text-sm font-bold text-slate-700">Display order<input type="number" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label></div><label className="mt-4 block text-sm font-bold text-slate-700">Description<textarea rows={2} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label><div className="mt-4 flex gap-3"><button disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-lg bg-[#0329B2] px-4 py-2.5 font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />Save</button><button onClick={reset} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 font-bold text-slate-700"><X className="h-4 w-4" />Cancel</button></div></section>}
    <section className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-8 text-slate-600">Loading categories…</p> : items.length === 0 ? <p className="p-8 text-slate-600">No active categories yet.</p> : <table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th className="p-4">Code</th><th className="p-4">Category</th><th className="p-4">Order</th><th className="p-4">Description</th><th className="p-4"><span className="sr-only">Actions</span></th></tr></thead><tbody>{items.map((item) => <tr key={item._id} className="border-t border-slate-100"><td className="p-4 font-mono text-xs font-bold text-slate-700">{item.code}</td><td className="p-4 font-bold text-slate-900">{item.name}</td><td className="p-4 text-slate-600">{item.displayOrder}</td><td className="p-4 text-slate-600">{item.description || "—"}</td><td className="p-4"><div className="flex gap-3"><button onClick={() => { setEditing(item._id); setForm({ code: item.code, name: item.name, description: item.description || "", displayOrder: String(item.displayOrder || 0) }); setOpen(true); }} className="inline-flex items-center gap-1 font-bold text-[#0329B2]"><Pencil className="h-4 w-4" />Edit</button><button onClick={() => void archive(item)} className="inline-flex items-center gap-1 font-bold text-red-700"><Archive className="h-4 w-4" />Archive</button></div></td></tr>)}</tbody></table>}</section></main>;
}
