"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ExternalLink, Filter } from "lucide-react";
import api from "@/lib/axios";
import { showError } from "@/lib/toast";

type Approval = { profileId: string; tutorName: string; tutorEmail: string; subject: string; levels: string[]; status: string; eligibilityType: string; evidenceRequired: boolean; requestedAt?: string; reason?: string };
const pill: Record<string, string> = { pending: "bg-amber-100 text-amber-800", needs_evidence: "bg-orange-100 text-orange-800", approved: "bg-emerald-100 text-emerald-800", rejected: "bg-red-100 text-red-800", revoked: "bg-red-100 text-red-800", suspended: "bg-slate-200 text-slate-800" };
export default function TutorApprovalsPage() {
  const [status, setStatus] = useState("pending,needs_evidence"); const [items, setItems] = useState<Approval[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); api.get(`/admin/academic-framework/tutor-approvals?status=${encodeURIComponent(status)}`).then(({ data }) => setItems(data.approvals || [])).catch((error) => showError(error, "Could not load tutor subject approvals")).finally(() => setLoading(false)); }, [status]);
  return <main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#016EF8]">Academic framework</p><h1 className="mt-1 text-3xl font-extrabold text-slate-900">Tutor subject approvals</h1><p className="mt-2 max-w-3xl text-slate-600">Review pending teaching requests. Final actions stay on the tutor application, where document evidence and the full audit history are visible.</p>
    <label className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-slate-700"><Filter className="h-4 w-4" aria-hidden />Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2"><option value="pending,needs_evidence">Needs review</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All statuses</option></select></label>
    <section className="mt-4 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-8 text-slate-600">Loading review queue…</p> : items.length === 0 ? <p className="p-8 text-slate-600">No tutor subject requests match this filter.</p> : <table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th className="p-4">Tutor</th><th className="p-4">Requested subject</th><th className="p-4">Eligibility</th><th className="p-4">Status</th><th className="p-4">Requested</th><th className="p-4"><span className="sr-only">Review</span></th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.profileId}-${item.subject}-${index}`} className="border-t border-slate-100"><td className="p-4"><p className="font-bold text-slate-900">{item.tutorName}</p><p className="text-slate-500">{item.tutorEmail}</p></td><td className="p-4 font-semibold text-slate-800">{item.subject}{item.levels.length ? <p className="mt-1 text-xs font-normal text-slate-500">{item.levels.join(", ")}</p> : null}</td><td className="p-4 capitalize text-slate-700">{item.eligibilityType.replace("_", " ")}{item.evidenceRequired ? <p className="mt-1 text-xs text-orange-700">Evidence required</p> : null}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${pill[item.status] || pill.pending}`}>{item.status.replace("_", " ")}</span></td><td className="p-4 text-slate-600">{item.requestedAt ? new Date(item.requestedAt).toLocaleDateString() : "—"}</td><td className="p-4"><Link className="inline-flex items-center gap-1 font-bold text-[#0329B2] hover:underline" href={`/admin/applications/${item.profileId}`}>Review <ExternalLink className="h-4 w-4" aria-hidden /></Link></td></tr>)}</tbody></table>}</section></main>;
}
