"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, RefreshCw, TrendingUp } from "lucide-react";
import api from "@/lib/axios";

type Score = { score: number; grade: string; components: { demandScore: number; supplyScore: number; fillRateScore: number; competitionScore: number }; meta: { openRequests: number; eligibleTutors: number; fillRate: number; avgOffersPerRequest: number; avgSessionPrice: number } };

export default function AdminLiquidityPage() {
  const [scores, setScores] = useState<Record<string, Score>>({});
  const [summary, setSummary] = useState<{ avgScore: number; totalSegments: number; high: number; moderate: number; low: number }>({ avgScore: 0, totalSegments: 0, high: 0, moderate: 0, low: 0 });
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const response = await api.get("/liquidity/overview", { params: { countryCode: "PK" } }); setScores(response.data?.scores || {}); setSummary(response.data?.summary || summary); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const rows = Object.entries(scores).sort(([, a], [, b]) => b.score - a.score);
  return <div style={{ padding: "1.75rem 2rem", color: "#0f172a" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: "1rem", flexWrap: "wrap", marginBottom: "1.5rem" }}><div><Link href="/admin" style={{ color: "#64748b", textDecoration: "none", display: "inline-flex", gap: ".35rem", alignItems: "center", fontSize: ".8rem", fontWeight: 700 }}><ArrowLeft size={14} /> Control Tower</Link><h1 style={{ margin: ".5rem 0 .25rem", fontSize: "1.6rem", fontWeight: 900 }}>Marketplace liquidity scores</h1><p style={{ color: "#64748b", margin: 0, fontSize: ".85rem" }}>Demand, eligible supply, fill rate, and offer competition by city, subject, and mode.</p></div><button type="button" onClick={() => void load()} disabled={loading} style={styles.button}><RefreshCw size={15} /> {loading ? "Refreshing…" : "Refresh"}</button></div><div style={styles.summary}>{[[summary.avgScore,"Average score"],[summary.totalSegments,"Segments"],[summary.high,"High"],[summary.moderate,"Moderate"],[summary.low,"Low"]].map(([value,label]) => <div key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div><div style={styles.tableWrap}>{loading ? <p style={styles.empty}>Calculating live liquidity…</p> : rows.length === 0 ? <p style={styles.empty}>No demand segments are available yet.</p> : <div style={{ overflowX: "auto" }}><table style={styles.table}><thead><tr>{["Segment","Score","Grade","Demand","Supply","Fill rate","Offers/request","Avg session rate"].map((h) => <th key={h} style={styles.th}>{h}</th>)}</tr></thead><tbody>{rows.map(([key, value]) => <tr key={key}><td style={styles.td}><strong>{key.split("|")[0]}</strong><br /><span style={{ color: "#64748b" }}>{key.split("|").slice(1).join(" · ")}</span></td><td style={styles.td}><span style={{ ...styles.score, background: value.score >= 75 ? "#dcfce7" : value.score >= 50 ? "#fef3c7" : "#fee2e2", color: value.score >= 75 ? "#166534" : value.score >= 50 ? "#92400e" : "#991b1b" }}>{value.score}/100</span></td><td style={styles.td}>{value.grade}</td><td style={styles.td}>{value.meta.openRequests} open</td><td style={styles.td}>{value.meta.eligibleTutors} eligible</td><td style={styles.td}>{Math.round(value.meta.fillRate * 100)}%</td><td style={styles.td}>{value.meta.avgOffersPerRequest}</td><td style={styles.td}>{value.meta.avgSessionPrice ? `PKR ${value.meta.avgSessionPrice.toLocaleString()}` : "—"}</td></tr>)}</tbody></table></div>}</div><p style={{ color: "#64748b", fontSize: ".75rem", marginTop: "1rem" }}><TrendingUp size={13} style={{ verticalAlign: "middle" }} /> Scores are operational signals, not guarantees of tutor availability. Use the At-Risk Requests queue for interventions.</p></div>;
}

const styles: Record<string, React.CSSProperties> = { button: { display: "inline-flex", alignItems: "center", gap: ".4rem", background: "white", border: "1px solid #cbd5e1", borderRadius: ".5rem", padding: ".6rem .85rem", fontWeight: 800, cursor: "pointer" }, summary: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(125px,1fr))", gap: ".75rem", marginBottom: "1.25rem" }, tableWrap: { background: "white", border: "1px solid #e2e8f0", borderRadius: ".8rem", overflow: "hidden" }, empty: { padding: "3rem", textAlign: "center", color: "#64748b" }, table: { width: "100%", borderCollapse: "collapse", minWidth: 800 }, th: { textAlign: "left", padding: ".75rem", background: "#f1f5f9", fontSize: ".72rem", color: "#475569" }, td: { padding: ".8rem .75rem", borderBottom: "1px solid #f1f5f9", fontSize: ".78rem", verticalAlign: "top" }, score: { display: "inline-block", borderRadius: 999, padding: ".25rem .5rem", fontWeight: 850, fontSize: ".72rem" } };
