services:
  - type: web
    name: tutorera-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RESEND
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SWICH_CLIENT_ID
        sync: false
      - key: SWICH_CLIENT_SECRET
        sync: false
      - key: SWICH_ENVIRONMENT
        value: sandbox
      - key: SWICH_AUTH_BASE_URL
        sync: false
      - key: SWICH_API_BASE_URL
        sync: false
      - key: SWICH_SUPPORTED_MARKETS
        value: PK
      - key: SWICH_SUPPORTED_CURRENCIES
        value: PKR
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
