"use client";

import { useEffect, useState } from "react";
import { Plus, Save } from "lucide-react";
import api from "@/lib/axios";
import { showError, showSuccess } from "@/lib/toast";

type Option = { _id: string; code: string; name: string };
type Rule = { _id: string; eligibilityType: "direct" | "conditional"; evidenceRequired: boolean; minimumDegreeLevel?: string; notes?: string; discipline: Option; subject: Option };

export default function TeachingEligibilityPage() {
  const [rules, setRules] = useState<Rule[]>([]); const [disciplines, setDisciplines] = useState<Option[]>([]); const [subjects, setSubjects] = useState<Option[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ disciplineId: "", subjectId: "", eligibilityType: "direct", minimumDegreeLevel: "", notes: "" });
  const load = async () => { setLoading(true); try { const [rulesResult, disciplineResult, subjectResult] = await Promise.all([api.get("/admin/academic-framework/eligibility-rules?status=active"), api.get("/admin/academic-framework/disciplines?status=active"), api.get("/admin/academic-framework/subjects?status=active")]); setRules(rulesResult.data.rules || []); setDisciplines(disciplineResult.data.disciplines || []); setSubjects(subjectResult.data.subjects || []); } catch (error) { showError(error, "Could not load teaching eligibility"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async () => { if (!form.disciplineId || !form.subjectId) return showError("Choose both a discipline and a subject"); setSaving(true); try { await api.post("/admin/academic-framework/eligibility-rules", form); showSuccess("Teaching eligibility rule created"); setForm({ disciplineId: "", subjectId: "", eligibilityType: "direct", minimumDegreeLevel: "", notes: "" }); await load(); } catch (error) { showError(error, "Could not save teaching eligibility rule"); } finally { setSaving(false); } };
  return <main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#016EF8]">Academic framework</p><h1 className="mt-1 text-3xl font-extrabold text-slate-900">Teaching Eligibility</h1><p className="mt-2 max-w-3xl text-slate-600">A rule determines whether a verified qualification in a discipline can support a tutor’s subject request. It never grants marketplace approval by itself.</p>
    <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Create rule</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-bold text-slate-700">Discipline<select value={form.disciplineId} onChange={(e) => setForm({ ...form, disciplineId: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal"><option value="">Select discipline</option>{disciplines.map((item) => <option value={item._id} key={item._id}>{item.code} — {item.name}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Teaching subject<select value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal"><option value="">Select subject</option>{subjects.map((item) => <option value={item._id} key={item._id}>{item.code} — {item.name}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Eligibility<select value={form.eligibilityType} onChange={(e) => setForm({ ...form, eligibilityType: e.target.value as "direct" | "conditional" })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal"><option value="direct">Direct</option><option value="conditional">Conditional — evidence required</option></select></label><label className="text-sm font-bold text-slate-700">Minimum degree level<input value={form.minimumDegreeLevel} onChange={(e) => setForm({ ...form, minimumDegreeLevel: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" placeholder="e.g. Bachelors" /></label></div><label className="mt-4 block text-sm font-bold text-slate-700">Review guidance / notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" rows={2} placeholder="Explain why this rule exists or what evidence a reviewer needs." /></label><button disabled={saving} onClick={() => void submit()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#0329B2] px-4 py-2.5 font-bold text-white disabled:opacity-50">{saving ? <Save className="h-4 w-4 animate-pulse" /> : <Plus className="h-4 w-4" />}Create rule</button></section>
    <section className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-8 text-slate-600">Loading teaching eligibility rules…</p> : rules.length === 0 ? <p className="p-8 text-slate-600">No active rules yet. Create a direct or conditional rule above.</p> : <table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th className="p-4">Qualification discipline</th><th className="p-4">Teaching subject</th><th className="p-4">Rule</th><th className="p-4">Minimum degree</th><th className="p-4">Review guidance</th></tr></thead><tbody>{rules.map((rule) => <tr key={rule._id} className="border-t border-slate-100"><td className="p-4 font-semibold text-slate-800">{rule.discipline?.code} <span className="font-normal text-slate-500">{rule.discipline?.name}</span></td><td className="p-4 font-semibold text-slate-800">{rule.subject?.code} <span className="font-normal text-slate-500">{rule.subject?.name}</span></td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${rule.eligibilityType === "direct" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{rule.eligibilityType}{rule.evidenceRequired ? " · evidence" : ""}</span></td><td className="p-4 text-slate-600">{rule.minimumDegreeLevel || "—"}</td><td className="p-4 text-slate-600">{rule.notes || "—"}</td></tr>)}</tbody></table>}</section>
  </main>;
}
