import type { Metadata } from "next";
import Link from "next/link";
export const metadata:Metadata={title:"How Tutor Offers Work | Compare & Choose Tutors",description:"Post a tuition request, propose a budget, compare verified tutor offers, negotiate transparently, and choose your tutor on TUTORERA.",alternates:{canonical:"/how-tutor-offers-work"}};
const faq=[
 ["How do students receive tutor offers?","A student publishes a tuition request with learning, mode, schedule, location and budget details. Eligible verified tutors can respond while the request remains open."],
 ["Can students set their own tutoring budget?","Yes. Students choose a proposed rate and pricing unit. An optional maximum budget remains private and is not shown to tutors."],
 ["Can tutors offer a different rate?","Yes, when counter-offers are enabled. A tutor may accept the proposed rate or submit another rate."],
 ["Can students negotiate tutor rates?","Yes. Each side may make up to three counter-offers. Every change is added to an immutable timeline and expired offers cannot be accepted."],
 ["Does TUTORERA choose the tutor?","No. Students compare relevance, qualifications, experience, verified-booking reviews, availability and pricing."],
 ["What happens after accepting an offer?","The rate is locked, other offers close, and a booking snapshots the applicable fees. Payment is then required before activation."]
];
export default function Page(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};return <main style={{color:"#021550"}}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header style={{background:"#021550",color:"white",padding:"5rem 1.5rem",textAlign:"center"}}><h1 style={{fontSize:"clamp(2rem,5vw,3.4rem)"}}>How TUTORERA Tutor Offers Work</h1><p style={{maxWidth:760,margin:"1rem auto",lineHeight:1.8,color:"#cbd5e1"}}>Set your requirements. Receive offers. Compare tutors. Agree on a rate. Learn with confidence.</p><Link href="/dashboard" style={{display:"inline-block",background:"#0329B2",color:"white",padding:".8rem 1.4rem",borderRadius:8,textDecoration:"none",fontWeight:700}}>Post a Tuition Request</Link></header><div style={{maxWidth:850,margin:"auto",padding:"3.5rem 1.5rem"}}><section><h2>Pakistan&apos;s student-led tutor marketplace</h2><p style={{lineHeight:1.8,color:"#475569"}}>TUTORERA is a Pakistan-based tutoring marketplace where students and parents can post tutoring requirements and specify a preferred budget. Eligible verified tutors may accept the proposed rate or submit an alternative offer. Students can compare tutors by qualifications, experience, reviews, availability and pricing before choosing a tutor.</p></section><section style={{marginTop:40}}><h2>The five-step process</h2><ol style={{lineHeight:2,color:"#475569"}}><li><strong>Tell us what you need:</strong> subject, level, curriculum, goal, mode, approximate location, schedule and budget.</li><li><strong>Receive tutor offers:</strong> matching verified tutors accept the rate or counter.</li><li><strong>Compare and negotiate:</strong> review evidence, match score, availability, pricing and history.</li><li><strong>Choose your tutor:</strong> accept the tutor and immutable final rate that suit you.</li><li><strong>Pay and begin:</strong> review fees, complete payment, and activate the booking.</li></ol></section><section style={{marginTop:40,background:"#f8fafc",padding:24,borderRadius:14}}><h2>TUTORERA Marketplace Principles</h2><ul style={{lineHeight:1.9,color:"#475569"}}><li>Students control which tutor they select.</li><li>Tutors set their own rates and are never forced to accept.</li><li>Students may propose a budget; tutors may accept or counter.</li><li>Rankings consider relevance and quality, not only price.</li><li>Charges and estimated tutor earnings are disclosed before commitment.</li><li>Private contacts and exact addresses remain protected until appropriate safeguards are complete.</li></ul></section><section style={{marginTop:40}}><h2>Common questions</h2>{faq.map(([q,a])=><details key={q} style={{borderBottom:"1px solid #e2e8f0",padding:"1rem 0"}}><summary style={{fontWeight:700,cursor:"pointer"}}>{q}</summary><p style={{color:"#475569",lineHeight:1.7}}>{a}</p></details>)}</section></div></main>}
