"use client";

import { useEffect, useState } from "react";
import { Archive, Pencil, Plus, Save, X } from "lucide-react";
import api from "@/lib/axios";
import { showError, showSuccess } from "@/lib/toast";

type Category = { _id: string; code: string; name: string };
type Subject = { _id: string; code?: string; name: string; description?: string; status?: string; displayOrder?: number; categoryRef?: Category; category?: string };
const empty = { code: "", name: "", categoryId: "", description: "", displayOrder: "0" };

export default function SubjectCataloguePage() {
  const [subjects, setSubjects] = useState<Subject[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [showForm, setShowForm] = useState(false);
  const load = async () => { setLoading(true); try { const [subjectResult, categoryResult] = await Promise.all([api.get("/admin/academic-framework/subjects?status=active&limit=100"), api.get("/admin/academic-framework/categories?status=active&limit=100")]); setSubjects(subjectResult.data.subjects || []); setCategories(categoryResult.data.categories || []); } catch (error) { showError(error, "Could not load the subject catalogue"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const reset = () => { setForm(empty); setEditing(null); setShowForm(false); };
  const submit = async () => { if (!form.name.trim() || !form.categoryId) return showError("Subject name and category are required"); setSaving(true); const payload = { ...form, displayOrder: Number(form.displayOrder) || 0 }; try { if (editing) { await api.patch(`/admin/academic-framework/subjects/${editing}`, payload); showSuccess("Subject updated"); } else { await api.post("/admin/academic-framework/subjects", payload); showSuccess("Subject created"); } reset(); await load(); } catch (error) { showError(error, "Could not save subject"); } finally { setSaving(false); } };
  const edit = (subject: Subject) => { setEditing(subject._id); setForm({ code: subject.code || "", name: subject.name, categoryId: subject.categoryRef?._id || "", description: subject.description || "", displayOrder: String(subject.displayOrder || 0) }); setShowForm(true); };
  const archive = async (subject: Subject) => { if (!window.confirm(`Archive ${subject.name}? It will remain on historical records but cannot be selected going forward.`)) return; try { await api.patch(`/admin/academic-framework/subjects/${subject._id}`, { status: "archived" }); showSuccess("Subject archived"); await load(); } catch (error) { showError(error, "Could not archive subject"); } };
  return <main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#016EF8]">Academic framework</p><h1 className="mt-1 text-3xl font-extrabold text-slate-900">Subject Catalogue</h1><p className="mt-2 max-w-3xl text-slate-600">Subjects are what students request and tutors may ultimately be approved to teach. They are distinct from qualification disciplines.</p>
    <div className="mt-6 flex flex-wrap gap-3"><button onClick={() => { reset(); setShowForm(true); }} className="inline-flex items-center gap-2 rounded-lg bg-[#0329B2] px-4 py-2.5 font-bold text-white"><Plus className="h-4 w-4" />New subject</button></div>
    {showForm && <section className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-bold text-slate-900">{editing ? "Edit subject" : "Create subject"}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-bold text-slate-700">Stable code<input value={form.code} disabled={Boolean(editing)} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="SUB-MATH" className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal disabled:bg-slate-100" /></label><label className="text-sm font-bold text-slate-700">Subject name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label><label className="text-sm font-bold text-slate-700">Category<select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal"><option value="">Select category</option>{categories.map((category) => <option key={category._id} value={category._id}>{category.code} — {category.name}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Display order<input type="number" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label></div><label className="mt-4 block text-sm font-bold text-slate-700">Description<textarea rows={2} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label><div className="mt-4 flex gap-3"><button onClick={() => void submit()} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#0329B2] px-4 py-2.5 font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />Save subject</button><button onClick={reset} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 font-bold text-slate-700"><X className="h-4 w-4" />Cancel</button></div></section>}
    <section className="mt-6 overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-8 text-slate-600">Loading subjects…</p> : subjects.length === 0 ? <p className="p-8 text-slate-600">No active subjects yet. Create one or use the CSV import centre.</p> : <table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th className="p-4">Code</th><th className="p-4">Subject</th><th className="p-4">Category</th><th className="p-4">Order</th><th className="p-4"><span className="sr-only">Actions</span></th></tr></thead><tbody>{subjects.map((subject) => <tr className="border-t border-slate-100" key={subject._id}><td className="p-4 font-mono text-xs font-bold text-slate-700">{subject.code || "Legacy"}</td><td className="p-4"><p className="font-bold text-slate-900">{subject.name}</p><p className="mt-1 text-xs text-slate-500">{subject.description || "No description"}</p></td><td className="p-4 text-slate-700">{subject.categoryRef ? `${subject.categoryRef.code} — ${subject.categoryRef.name}` : subject.category || "Uncategorised"}</td><td className="p-4 text-slate-600">{subject.displayOrder || 0}</td><td className="p-4"><div className="flex gap-3"><button onClick={() => edit(subject)} className="inline-flex items-center gap-1 font-bold text-[#0329B2]"><Pencil className="h-4 w-4" />Edit</button><button onClick={() => void archive(subject)} className="inline-flex items-center gap-1 font-bold text-red-700"><Archive className="h-4 w-4" />Archive</button></div></td></tr>)}</tbody></table>}</section>
  </main>;
}
